/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedReadingRouteImport } from './routes/_authenticated/reading'
import { Route as AuthenticatedContributeRouteImport } from './routes/_authenticated/contribute'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedReadingIndexRouteImport } from './routes/_authenticated/reading.index'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections.index'
import { Route as AuthenticatedReadingIdRouteImport } from './routes/_authenticated/reading.$id'
import { Route as AuthenticatedCollectionsIdRouteImport } from './routes/_authenticated/collections.$id'

const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadingRoute = AuthenticatedReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContributeRoute = AuthenticatedContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReadingIndexRoute =
  AuthenticatedReadingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReadingRoute,
  } as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)
const AuthenticatedReadingIdRoute = AuthenticatedReadingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedReadingRoute,
} as any)
const AuthenticatedCollectionsIdRoute =
  AuthenticatedCollectionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCollectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/contribute': typeof AuthenticatedContributeRoute
  '/reading': typeof AuthenticatedReadingRouteWithChildren
  '/stats': typeof AuthenticatedStatsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/reading/$id': typeof AuthenticatedReadingIdRoute
  '/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/reading/': typeof AuthenticatedReadingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof AuthenticatedContributeRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/reading/$id': typeof AuthenticatedReadingIdRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/reading': typeof AuthenticatedReadingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRouteWithChildren
  '/_authenticated/contribute': typeof AuthenticatedContributeRoute
  '/_authenticated/reading': typeof AuthenticatedReadingRouteWithChildren
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/_authenticated/reading/$id': typeof AuthenticatedReadingIdRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/_authenticated/reading/': typeof AuthenticatedReadingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/collections'
    | '/contribute'
    | '/reading'
    | '/stats'
    | '/study'
    | '/collections/$id'
    | '/reading/$id'
    | '/collections/'
    | '/reading/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/contribute'
    | '/stats'
    | '/study'
    | '/collections/$id'
    | '/reading/$id'
    | '/collections'
    | '/reading'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/_authenticated/collections'
    | '/_authenticated/contribute'
    | '/_authenticated/reading'
    | '/_authenticated/stats'
    | '/_authenticated/study'
    | '/_authenticated/collections/$id'
    | '/_authenticated/reading/$id'
    | '/_authenticated/collections/'
    | '/_authenticated/reading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reading': {
      id: '/_authenticated/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof AuthenticatedReadingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contribute': {
      id: '/_authenticated/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof AuthenticatedContributeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reading/': {
      id: '/_authenticated/reading/'
      path: '/'
      fullPath: '/reading/'
      preLoaderRoute: typeof AuthenticatedReadingIndexRouteImport
      parentRoute: typeof AuthenticatedReadingRoute
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
    '/_authenticated/reading/$id': {
      id: '/_authenticated/reading/$id'
      path: '/$id'
      fullPath: '/reading/$id'
      preLoaderRoute: typeof AuthenticatedReadingIdRouteImport
      parentRoute: typeof AuthenticatedReadingRoute
    }
    '/_authenticated/collections/$id': {
      id: '/_authenticated/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AuthenticatedCollectionsIdRouteImport
      parentRoute: typeof AuthenticatedCollectionsRoute
    }
  }
}

interface AuthenticatedCollectionsRouteChildren {
  AuthenticatedCollectionsIdRoute: typeof AuthenticatedCollectionsIdRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
}

const AuthenticatedCollectionsRouteChildren: AuthenticatedCollectionsRouteChildren =
  {
    AuthenticatedCollectionsIdRoute: AuthenticatedCollectionsIdRoute,
    AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
  }

const AuthenticatedCollectionsRouteWithChildren =
  AuthenticatedCollectionsRoute._addFileChildren(
    AuthenticatedCollectionsRouteChildren,
  )

interface AuthenticatedReadingRouteChildren {
  AuthenticatedReadingIdRoute: typeof AuthenticatedReadingIdRoute
  AuthenticatedReadingIndexRoute: typeof AuthenticatedReadingIndexRoute
}

const AuthenticatedReadingRouteChildren: AuthenticatedReadingRouteChildren = {
  AuthenticatedReadingIdRoute: AuthenticatedReadingIdRoute,
  AuthenticatedReadingIndexRoute: AuthenticatedReadingIndexRoute,
}

const AuthenticatedReadingRouteWithChildren =
  AuthenticatedReadingRoute._addFileChildren(AuthenticatedReadingRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRouteWithChildren
  AuthenticatedContributeRoute: typeof AuthenticatedContributeRoute
  AuthenticatedReadingRoute: typeof AuthenticatedReadingRouteWithChildren
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRouteWithChildren,
  AuthenticatedContributeRoute: AuthenticatedContributeRoute,
  AuthenticatedReadingRoute: AuthenticatedReadingRouteWithChildren,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
